;THIS PROGRAM IS A BOILERPLATE FILE SYSTEM DRIVER (FSD)
;IT IS ABLE TO INTERFACE WITH THE MICRON OPERATING SYSTEM
;AND RESPOND TO CALLS FROM THE CONSOLE PROGRAM
;
;THIS CAN ACT AS A TEMPLATE FOR ANYBODY LOOKING TO CREATE
;A CUSTOM FSD FOR ANY FILE SYSTEMS OR DEVICES ON THIR SYSTEM
;
BYTE A = 1
BYTE C = 128
BYTE E = 0
BYTE I = 0
STRING FILENAM[8] = ""
STRING FILEEXT[3] = ""
STRING DRVNAM[2] = ""
SHORT SECNUM = 0
SHORT IO = 0
BYTE SUBDEV = 0
BYTE DIRNUM = 0
BYTE COMMAND = 0
BYTE STATE = 0
BYTE FILEERR = 0
@START
	LET #COM[A] = #COM[C]
	IF #COM[A] = 0 GOTO KILL
	INC A
	INC C
	IF A = 2 GOTO START
	LET DRVNAM[0] = #COM[1]
	LET DRVNAM[1] = #COM[2]
	IF #COM[C] > 0 GOTO KILL
	PIPE IO,E
	IF E > 0 GOTO KILL
	LET #COM[3] = IO[0]
	LET #COM[4] = IO[1]
	LET #COM[0] = 33
	GOSUB WAIT
	IF #COM[126] > 0 GOTO KILL
	LET #COM[0] = 254
	GOSUB WAIT
DRVLOOP:
	GOSUB HANDRV
	GOTO DRVLOOP
	
DETACH:
	LET C = 18
	GOSUB SENDSTAT
	;THIS FUNCTION WILL REMOVE DETACH THE DRIVER FROM THE CONSOLE
	;IT WILL PREPARE THE PROCESS TO BE REMOVED FROM MEMORY
	LET #COM[1] = DRVNAM[0]
	LET #COM[2] = DRVNAM[1]
	LET #COM[0] = 34
	GOSUB WAIT

KILL:
	GETPID A
	LET #COM[1] = A
	LET #COM[0] = 255
HALT:
	FORFIT
	GOTO HALT
WAIT:
	FORFIT
	IF #COM[0] > 0 GOTO WAIT
	RETURN
	
HANDRV:
	GOSUB PULLC
	IF COMMAND = 0 GOTO PROCCOM
	IF COMMAND = 1 GOSUB READSEC
	IF COMMAND = 2 GOSUB WRITSEC
	IF COMMAND = 3 GOSUB CREATEFI
	IF COMMAND = 4 GOSUB REMOVEFI
	IF COMMAND = 7 GOSUB GETSTAT
	IF COMMAND = 8 GOSUB GOMNT
	IF COMMAND = 9 GOSUB GOUMNT
	IF COMMAND = 10 GOSUB GOFORM
	IF COMMAND = 11 GOSUB GETDIR
	IF COMMAND = 12 GOSUB GETSIZE
	RETURN

PROCCOM:
	IF C > 12 GOTO RET
	LET COMMAND = C
	LET STATE = 0
	LET I = 0
	LET FILEERR = 0
	RETURN
	
READSEC:
	GOSUB PROCARGS
	IF STATE < 5 GOTO RET
	
	;THIS ROUTINE WILL READ A SPECIFIED SECTOR NUMBER
	;FROM A SUBDEVICE. IT WILL OUTPUT THE STATUS IF
	;READY, AND THEN SEND THE 128 BYTE SECTOR. OTHERWISE
	;IT WILL RETURN A MICRON ERROR CODE
	
	LET C = 18
	GOTO SENDSTAT
	
WRITSEC:
	GOSUB PROCARGS
	IF STATE < 5 GOTO RET
	
	;THIS ROUTINE WILL WRITE A SPECIFIED SECTOR NUMBER
	;IN A SUBDEVICE. IT WILL OUTPUT THE STATUS IF
	;READY, AND THEN RECIEVE THE 128 BYTE SECTOR. OTHERWISE
	;IT WILL RETURN A MICRON ERROR CODE
	
	LET C = 18
	GOTO SENDSTAT
	
CREATEFI:
	GOSUB PROCARGS
	IF STATE < 5 GOTO RET
	
	;THIS ROUTINE WILL CREATE A FILE WITH A SPECIFIED SECTOR
	;COUNT FROM IN A SUBDEVICE. IT WILL OUTPUT THE STATUS IF
	;SUCCESSFUL, OTHERWISE IT WILL RETURN A MICRON ERROR CODE
	
	LET C = 18
	GOTO SENDSTAT
	
PROCARGS:
	IF STATE = 2 GOSUB SETSC1
	IF STATE = 1 GOSUB SETSC0
	IF STATE = 0 GOSUB SETSUB
	IF STATE > 2 GOSUB SETFI
	RETURN
	
REMOVEFI:
	IF STATE > 0 GOTO REMOVEFI1
	LET SUBDEV = C
	LET STATE = 3
	RETURN
	
REMOVEFI1:
	IF STATE > 2 GOSUB SETFI
	IF STATE < 5 GOTO RET
	
	;THIS ROUTINE WILL DELETE A FILE FROM A SPECIFIED SUBDEVICE
	;THIS WILL OUTPUT THE STATUS IF THE FILE WAS REMOVE, AND
	;RETURN A MICRON ERROR CODE IF IT HAS NOT.
	
	LET C = 18
	GOTO SENDSTAT
	
	
GETSTAT:
	GOSUB SETSUB
	
	;THIS ROUTINE WILL RETURN THE STATUS OF THE SUBDEVICE
	;0 IF READY, 255 IF NOT READY
	
	LET C = 255
	GOTO SENDSTAT

GOMNT:
	GOSUB SETSUB
	
	;THIS ROUTINE WILL MOUNT THE SELECTED SUBDEVICE. IT WILL OUTPUT
	;THE STATUS IF IT HAS BEEN ABLE TO MOUNT THE DEVICE
	
	LET C = 18
	GOTO SENDSTAT
	
GOUMNT:
	GOSUB SETSUB
	IF SUBDEV = 254 GOTO DETACH
	;THIS ROUTINE WILL UNMOUNT THE SELECTED SUBDEVICE. IT WILL OUTPUT
	;THE STATUS IF IT HAS BEEN ABLE TO UNMOUNT THE DEVICE
	
	LET C = 18
	GOTO SENDSTAT
	
GOFORM:
	GOSUB SETSUB
	
	;THIS ROUTINE WILL FORMAT THE SELECTED SUBDEVICE. IT WILL OUTPUT
	;THE STATUS IF IT HAS BEEN ABLE TO FORMAT THE DEVICE
	
	LET C = 18
	GOTO SENDSTAT
	
GETDIR:
	IF STATE = 0 GOTO SETSUB
	LET DIRNUM = C
	
	;THIS ROUTINE WILL RETURN A DIRECTORY ENTRY OF THE SELECTED
	;SUBDEVICE. IT WILL OUTPUT ITS STATUS, THEN IT WILL OUTPUT
	;A DIRECTORY ENTRY IF READY AND VALID
	
	LET C = 16
	GOTO SENDSTAT
	
	
GETSIZE:
	GOSUB SETSUB
	
	;THIS ROUTINE WILL RETURN THE SIZE OF THE SELECTED SUBDEVICE
	;IT WILL OUTPUT ITS STATUS, THEN IT WILL OUTPUT THE 3 BYTES TO
	;INDICATE THE SIZE IN SECTORS (LITTLE ENDIAN)
	
	LET C = 0
	GOSUB PUTC
	GOSUB PUTC
	GOSUB PUTC
	GOSUB PUTC
	LET COMMAND = 0
	RETURN
	
SETSUB:
	INC STATE
	LET SUBDEV = C
	RETURN
	
SETSC0:
	INC STATE
	LET SECNUM[0] = C
	RETURN
	
SETSC1:
	INC STATE
	LET SECNUM[1] = C
	RETURN

SETFI:
	IF C = 0 GOTO FICONT
	IF FILEERR = 1 GOTO WAITZERO
	IF STATE = 4 GOTO SETEXT
	IF C = 46 GOTO SETFI1
	IF I = 8 GOTO WAITZERO
	LET FILENAM[I] = C
	INC I
	RETURN
SETFI1:
	LET I = 0
	LET STATE = 4
	RETURN

SETEXT:
	IF I = 3 GOTO WAITZERO
	LET FILEEXT[I] = C
	INC I
	RETURN
	
WAITZERO:
	LET STATE = 4
	LET FILEERR = 1
	IF C > 0 GOTO RET
FICONT:
	LET STATE = 5
	RETURN
	
	
SENDSTAT:
	GOSUB PUTC
	LET COMMAND = 0
	RETURN
	
	
RET:
	RETURN
PULLC:
	HREAD IO,C,E
	IF E > 0 GOTO PULLERR
	RETURN
PULLERR:
	FORFIT
	GOTO PULLC
PUTC:
	HWRITE IO,C,E
	IF E > 0 GOTO PERR
	RETURN
PERR:
	FORFIT
	GOTO PUTC